# Generated by Django 5.0.1 on 2025-11-02 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('plaid', 'Plaid'), ('quickbooks', 'QuickBooks'), ('stripe', 'Stripe')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_connections', to='users.organization')),
            ],
            options={
                'db_table': 'account_connections',
                'ordering': ['-created_at'],
            },
        ),
    ]
